'use client';

import { useState } from 'react';
import CalculatorsLayout from '@/components/calculators/Calculatorslayout';
import TermGlossary from '@/components/calculators/TermGlossary';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { useI18n } from '@/i18n/I18nProvider';

interface AgendaItem {
  topic: string;
  presenter: string;
  discussion: string;
  decision: string;
}

interface ActionItem {
  task: string;
  assignee: string;
  deadline: string;
}

function generateMeetingNotes(
  isKo: boolean,
  title: string,
  date: string,
  attendees: string,
  agendaItems: AgendaItem[],
  actionItems: ActionItem[]
): string {
  const L = (ko: string, en: string) => (isKo ? ko : en);
  const lines: string[] = [];

  lines.push(`# ${title || L('제목 없음', 'Untitled')}`);
  lines.push('');
  lines.push(`## ${L('회의 정보', 'Meeting Info')}`);
  lines.push(`- **${L('날짜:', 'Date:')}** ${date || L('날짜 미정', 'Date TBD')}`);
  lines.push(`- **${L('참석자:', 'Attendees:')}** ${attendees || L('참석자 미정', 'Attendees TBD')}`);
  lines.push('');

  if (agendaItems.length > 0 && agendaItems.some(item => item.topic)) {
    lines.push(`## ${L('안건 및 논의 사항', 'Agenda & Discussions')}`);
    lines.push('');
    agendaItems.forEach((item, i) => {
      if (item.topic) {
        lines.push(`### ${i + 1}. ${item.topic}`);
        if (item.presenter) lines.push(`- **${L('발표자:', 'Presenter:')}** ${item.presenter}`);
        if (item.discussion) lines.push(`- **${L('논의 내용:', 'Discussion:')}** ${item.discussion}`);
        if (item.decision) lines.push(`- **${L('결정 사항:', 'Decision:')}** ${item.decision}`);
        lines.push('');
      }
    });
  }

  if (actionItems.length > 0 && actionItems.some(item => item.task)) {
    lines.push(`## ${L('액션 아이템', 'Action Items')}`);
    lines.push('');
    lines.push(`| ${L('작업', 'Task')} | ${L('담당자', 'Assignee')} | ${L('마감일', 'Deadline')} |`);
    lines.push('|------|--------|--------|');
    actionItems.forEach(item => {
      if (item.task) {
        lines.push(`| ${item.task} | ${item.assignee || L('미정', 'TBD')} | ${item.deadline || L('미정', 'TBD')} |`);
      }
    });
    lines.push('');
  }

  lines.push(`## ${L('메모', 'Notes')}`);
  lines.push('');
  lines.push('- [ ] ');
  lines.push('');
  lines.push('---');
  lines.push(`*${L('이 회의록은 회의록 작성기로 생성되었습니다.', 'This minutes document was generated by the Meeting Notes tool.')}*`);

  return lines.join('\n');
}

interface InfoSection {
  calculatorDescription: React.ReactNode;
  calculationFormula: React.ReactNode;
  containerSpecifications?: React.ReactNode;
  usefulTips: React.ReactNode;
}

interface MeetingNotesProps {
  infoSection: InfoSection;
}

const MeetingNotes = ({ infoSection }: MeetingNotesProps) => {
  const { dict, locale } = useI18n();
  const t = dict.meetingNotes;
  const isKo = locale === 'ko';
  const L = (ko: string, en: string) => (isKo ? ko : en);
  const [title, setTitle] = useState('');
  const [date, setDate] = useState('');
  const [attendees, setAttendees] = useState('');
  const [agendaItems, setAgendaItems] = useState<AgendaItem[]>([
    { topic: '', presenter: '', discussion: '', decision: '' },
  ]);
  const [actionItems, setActionItems] = useState<ActionItem[]>([
    { task: '', assignee: '', deadline: '' },
  ]);
  const [result, setResult] = useState('');

  const updateAgendaItem = (index: number, field: keyof AgendaItem, value: string) => {
    const updated = [...agendaItems];
    updated[index] = { ...updated[index], [field]: value };
    setAgendaItems(updated);
  };

  const addAgendaItem = () => {
    setAgendaItems([...agendaItems, { topic: '', presenter: '', discussion: '', decision: '' }]);
  };

  const removeAgendaItem = (index: number) => {
    if (agendaItems.length > 1) {
      setAgendaItems(agendaItems.filter((_, i) => i !== index));
    }
  };

  const updateActionItem = (index: number, field: keyof ActionItem, value: string) => {
    const updated = [...actionItems];
    updated[index] = { ...updated[index], [field]: value };
    setActionItems(updated);
  };

  const addActionItem = () => {
    setActionItems([...actionItems, { task: '', assignee: '', deadline: '' }]);
  };

  const removeActionItem = (index: number) => {
    if (actionItems.length > 1) {
      setActionItems(actionItems.filter((_, i) => i !== index));
    }
  };

  const generate = () => {
    setResult(generateMeetingNotes(isKo, title, date, attendees, agendaItems, actionItems));
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(result);
  };

  const inputSection = (
    <div className="space-y-4">
      <div className="space-y-2">
        <label className="text-sm font-medium">{t.titleLabel}</label>
        <Input
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder={t.titlePlaceholder}
        />
      </div>
      <div className="space-y-2">
        <label className="text-sm font-medium">{t.dateLabel}</label>
        <Input
          type="date"
          value={date}
          onChange={(e) => setDate(e.target.value)}
        />
      </div>
      <div className="space-y-2">
        <label className="text-sm font-medium">{t.attendeesLabel}</label>
        <Input
          value={attendees}
          onChange={(e) => setAttendees(e.target.value)}
          placeholder={t.attendeesPlaceholder}
        />
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium">{t.agendaLabel}</label>
        {agendaItems.map((item, i) => (
          <div key={i} className="p-3 bg-background border border-border rounded-lg space-y-2">
            <div className="flex justify-between items-center">
              <span className="text-xs font-medium text-muted-foreground">{t.agendaItemLabel.replace('{n}', String(i + 1))}</span>
              {agendaItems.length > 1 && (
                <Button variant="ghost" size="sm" onClick={() => removeAgendaItem(i)} className="h-6 text-xs">{t.deleteButton}</Button>
              )}
            </div>
            <Input
              value={item.topic}
              onChange={(e) => updateAgendaItem(i, 'topic', e.target.value)}
              placeholder={t.topicPlaceholder}
              className="h-8 text-xs"
            />
            <Input
              value={item.presenter}
              onChange={(e) => updateAgendaItem(i, 'presenter', e.target.value)}
              placeholder={t.presenterPlaceholder}
              className="h-8 text-xs"
            />
            <Textarea
              value={item.discussion}
              onChange={(e) => updateAgendaItem(i, 'discussion', e.target.value)}
              placeholder={t.discussionPlaceholder}
              className="min-h-[60px] text-xs"
            />
            <Input
              value={item.decision}
              onChange={(e) => updateAgendaItem(i, 'decision', e.target.value)}
              placeholder={t.decisionPlaceholder}
              className="h-8 text-xs"
            />
          </div>
        ))}
        <Button variant="outline" size="sm" onClick={addAgendaItem} className="w-full">{t.addAgendaButton}</Button>
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium">{t.actionLabel}</label>
        {actionItems.map((item, i) => (
          <div key={i} className="p-3 bg-background border border-border rounded-lg space-y-2">
            <div className="flex justify-between items-center">
              <span className="text-xs font-medium text-muted-foreground">{t.actionItemLabel.replace('{n}', String(i + 1))}</span>
              {actionItems.length > 1 && (
                <Button variant="ghost" size="sm" onClick={() => removeActionItem(i)} className="h-6 text-xs">{t.deleteButton}</Button>
              )}
            </div>
            <Input
              value={item.task}
              onChange={(e) => updateActionItem(i, 'task', e.target.value)}
              placeholder={t.taskPlaceholder}
              className="h-8 text-xs"
            />
            <div className="flex gap-2">
              <Input
                value={item.assignee}
                onChange={(e) => updateActionItem(i, 'assignee', e.target.value)}
                placeholder={t.assigneePlaceholder}
                className="h-8 text-xs"
              />
              <Input
                type="date"
                value={item.deadline}
                onChange={(e) => updateActionItem(i, 'deadline', e.target.value)}
                className="h-8 text-xs"
              />
            </div>
          </div>
        ))}
        <Button variant="outline" size="sm" onClick={addActionItem} className="w-full">{t.addActionButton}</Button>
      </div>

      <Button onClick={generate} className="w-full">{t.generateButton}</Button>
    </div>
  );

  const resultSection = result ? (
    <div className="space-y-3">
      <Button variant="outline" size="sm" onClick={copyToClipboard} className="w-full">{t.copyButton}</Button>
      <Textarea readOnly value={result} className="min-h-[400px] font-mono text-xs leading-relaxed" />
    </div>
  ) : (
    <div className="flex items-center justify-center text-muted-foreground h-full">
      {t.emptyPrompt}
    </div>
  );

  return (
    <CalculatorsLayout
      title={t.title}
      description={t.description}
      inputSection={inputSection}
      resultSection={resultSection}
      infoSection={infoSection}
      variant="split"
     />
  );
};

export default MeetingNotes;
