import TermGlossary from "@/components/calculators/TermGlossary";
import type { Metadata } from "next";
import { buildCalculatorMetadata } from "@/lib/calculatorSeo";
import FaqItem from "@/components/calculators/FaqItem";
import CalculatorClient from "./UrlDecoderClient";

export function generateMetadata({
  params,
}: {
  params: { locale: string };
}): Metadata {
  return buildCalculatorMetadata(params.locale, "/calculators/ai-tools/url-decoder", "ai-tools", "url-decoder");
}

export default function UrlDecoderPage({
  params,
}: {
  params: { locale: string };
}) {
  const isKo = params.locale === "ko";
  const L = (ko: string, en: string) => (isKo ? ko : en);

  const faqs: { q: string; a: string }[] = [
    {
      q: L("URL 디코딩은 언제 사용해야 하나요?", "When should I use URL decoding?"),
      a: L(
        "브라우저 주소창에 인코딩된 URL을 보고 싶을 때, 네트워크 요청이나 서버 로그에서 쿼리 파라미터를 해석할 때, 또는 다른 도구가 만든 인코딩된 링크를 읽을 때 사용합니다. 예를 들어 검색 결과 URL의 %20이 실제 공백임을 확인할 때 유용합니다.",
        "Use it to read encoded URLs in the browser address bar, interpret query parameters in server logs or network requests, or inspect links generated by other tools. For example, it reveals that %20 in a search URL is actually a space.",
      ),
    },
    {
      q: L("문자가 깨져 나오면 왜 그런가요?", "Why is the decoded text garbled?"),
      a: L(
        "원본 텍스트가 UTF-8이 아닌 다른 문자셋(예: EUC-KR, ISO-8859-1)으로 인코딩된 경우가 대부분입니다. 이 경우 %XX 코드가 가리키는 바이트가 다른 문자로 해석되어 깨져 보입니다. 해당 사이트가 어떤 문자셋을 사용하는지 확인해야 합니다.",
        "Usually because the original text used a different charset (e.g., EUC-KR, ISO-8859-1) rather than UTF-8. The %XX codes reference bytes that are interpreted as different characters, producing garbled output. Check what charset the source site used.",
      ),
    },
    {
      q: L("+와 %20의 차이는 무엇인가요?", "What is the difference between + and %20?"),
      a: L(
        "application/x-www-form-urlencoded 방식(HTML 폼)에서는 +가 공백을 의미합니다. 하지만 URL 경로나 일반 쿼리에서 공백은 %20으로 인코딩됩니다. 따라서 같은 문자열이더라도 폼 인코딩인지 URL 인코딩인지에 따라 디코딩 결과가 다를 수 있습니다.",
        "In application/x-www-form-urlencoded (HTML forms), + represents a space. But in URL paths and regular query strings, a space is encoded as %20. So the same string may decode differently depending on whether it used form or URL encoding.",
      ),
    },
    {
      q: L("decode와 decodeURIComponent의 차이는 무엇인가요?", "What is the difference between decode and decodeURIComponent?"),
      a: L(
        "decodeURIComponent는 모든 퍼센트 인코딩 시퀀스를 해석하므로 %26, %3F 등도 디코딩합니다. 반면 decodeURI는 /, ?, # 등 URL 구조 문자에 해당하는 시퀀스는 보존합니다. 이 계산기는 전체 URL 구조를 유지할 필요가 없으므로 모든 문자를 디코딩합니다.",
        "decodeURIComponent decodes every percent-encoded sequence, including %26 and %3F. decodeURI preserves sequences that map to URL structure characters like /, ?, and #. This tool decodes everything because it does not need to preserve URL structure.",
      ),
    },
    {
      q: L("깨진(오류) 출력을 해결하려면 어떻게 해야 하나요?", "How do I fix garbled or wrong output?"),
      a: L(
        "먼저 입력이 유효한 퍼센트 인코딩인지 확인하고, 인코딩에 사용된 문자셋(주로 UTF-8)을 확인하세요. 원본이 UTF-8이라면 올바른 결과가 나옵니다. 일부 사이트는 이중 인코딩(예: %2520)을 사용하므로, 한 번 더 디코딩해야 할 수도 있습니다.",
        "First confirm the input is valid percent encoding and check the charset (usually UTF-8) used when encoding. Correct input in UTF-8 yields correct output. Some sites use double-encoding (e.g., %2520), which may require decoding twice.",
      ),
    },
  ];

  const infoSection = {
    calculatorDescription: (
      <div className="space-y-4">
        <p>
          <strong>URL Decoder</strong> converts percent-encoded (%XX) characters back to their original form. This is useful for reading encoded URLs, debugging web requests, and inspecting query parameters.
        </p>
        <p>
          The decoder handles all percent-encoded characters including spaces (%20), special characters (%21, %23, etc.), and non-ASCII characters (%E2%82%AC for Euro symbol).
        </p>
        <TermGlossary items={[
          { term: isKo ? 'URL 디코딩' : 'URL Decoding', desc: isKo ? '퍼센트 인코딩(%XX)된 문자열을 원래의 문자로 되돌리는 과정입니다. 웹 요청이나 쿼리 파라미터를 읽을 때 사용합니다.' : 'The process of converting a percent-encoded (%XX) string back to its original characters. Used when reading web requests or query parameters.' },
          { term: isKo ? '퍼센트 인코딩(%XX)' : 'Percent Encoding (%XX)', desc: isKo ? '문자를 %와 두 자리 16진수 ASCII 코드로 표현하는 방식입니다. 예를 들어 공백은 %20, &는 %26으로 나타냅니다.' : 'A scheme that represents characters as % followed by a two-digit hexadecimal ASCII code. For example, a space is %20 and & is %26.' },
        ]} />
      </div>
    ),
    calculationFormula: (
      <div className="space-y-4">
        <p className="font-semibold">Decoding Examples:</p>
        <div className="p-4 bg-gray-100 dark:bg-gray-800 rounded-lg space-y-2">
          <p className="font-mono text-xs">%20 → Space</p>
          <p className="font-mono text-xs">%21 → !</p>
          <p className="font-mono text-xs">%23 → #</p>
          <p className="font-mono text-xs">%26 → &</p>
          <p className="font-mono text-xs">%2B → +</p>
        </div>
        <p className="text-sm">
          The % symbol followed by two hexadecimal digits is converted back to the corresponding ASCII character.
        </p>
      </div>
    ),
    usefulTips: (
      <div className="space-y-4">
        <p className="font-semibold">Tips:</p>
        <ul className="space-y-2 text-sm">
          <li>Most browsers show decoded URLs in the address bar but encode them in network requests.</li>
          <li>If decoding produces garbled text, the original encoding might have used a different charset.</li>
          <li>URL encoding is case-sensitive: %2f is different from %2F.</li>
          <li>The + character in form-encoded data represents a space, but in URLs it stays as +.</li>
        </ul>
      </div>
    ),
    howToUse: (
      <ol className="space-y-4 text-sm text-muted-foreground">
        {[
          [
            L("인코딩된 URL 붙여넣기", "Paste the encoded URL"),
            L("주소창이나 네트워크 로그에서 가져온 %XX 형식의 문자열을 입력란에 붙여넣습니다.", "Paste the %XX-format string copied from the address bar or a network log into the input."),
          ],
          [
            L("디코드 버튼 클릭", "Click decode"),
            L("버튼을 누르면 각 %XX 시퀀스가 원래 문자로 변환되어 출력됩니다.", "Clicking the button converts each %XX sequence back to its original character."),
          ],
          [
            L("결과 확인", "Review the decoded output"),
            L("공백, 특수문자, 한글 등이 올바르게 복원되었는지 확인합니다.", "Check that spaces, special characters, and non-ASCII text were restored correctly."),
          ],
          [
            L("결과 복사", "Copy the result"),
            L("필요하면 디코딩된 텍스트를 복사 버튼으로 클립보드에 저장합니다.", "Use the copy button to save the decoded text to your clipboard if needed."),
          ],
        ].map(([title, body], i) => (
          <li key={i} className="flex gap-3">
            <span className="shrink-0 w-6 h-6 rounded-full bg-primary/10 text-primary font-bold flex items-center justify-center text-xs mt-0.5">{i + 1}</span>
            <div>
              <p className="font-semibold text-foreground">{title}</p>
              <p className="mt-1">{body}</p>
            </div>
          </li>
        ))}
      </ol>
    ),
    workedExamples: (
      <div className="space-y-6 text-sm text-muted-foreground">
        <div>
          <p className="font-semibold text-foreground mb-2">{L("예시 1 — 공백", "Example 1 — Space")}</p>
          <p className="font-mono text-xs">%20 → (space)</p>
          <p className="mt-2">
            {L(
              "'https://example.com/search?q=hello%20world'에서 %20은 공백입니다. 디코딩하면 'hello world'가 됩니다. 검색어나 파일명에 공백이 있을 때 %20으로 표시됩니다.",
              "In 'https://example.com/search?q=hello%20world', %20 is a space. Decoding it yields 'hello world'. Spaces appear as %20 in search queries and file names.",
            )}
          </p>
        </div>
        <div>
          <p className="font-semibold text-foreground mb-2">{L("예시 2 — 유로 기호", "Example 2 — Euro symbol")}</p>
          <p className="font-mono text-xs">%E2%82%AC → €</p>
          <p className="mt-2">
            {L(
              "비 ASCII 문자인 €는 UTF-8에서 3바이트로 인코딩되며, 각 바이트가 %E2%82%AC로 표현됩니다. 디코딩하면 원래의 유로 기호가 복원됩니다.",
              "The non-ASCII € character is encoded as 3 bytes in UTF-8, each represented as %E2%82%AC. Decoding restores the original euro symbol.",
            )}
          </p>
        </div>
        <div>
          <p className="font-semibold text-foreground mb-2">{L("예시 3 — 슬래시", "Example 3 — Slash")}</p>
          <p className="font-mono text-xs">%2F → /</p>
          <p className="mt-2">
            {L(
              "경로 구분자로 쓰이는 '/'는 encodeURIComponent에서 %2F로 인코딩됩니다. 경로 자체를 나눌 때와 구분하기 위해, 파라미터 안의 슬래시는 보통 %2F로 유지합니다.",
              "The '/' used as a path separator is encoded as %2F by encodeURIComponent. A slash inside a parameter is usually kept as %2F to distinguish it from path separators.",
            )}
          </p>
        </div>
      </div>
    ),
    faq: (
      <div className="space-y-5 text-sm text-muted-foreground">
        {faqs.map((f, i) => (
          <FaqItem key={i} q={f.q} a={f.a} />
        ))}
      </div>
    ),
  };

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map(f => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }}
      />
      <CalculatorClient infoSection={infoSection} />
    </>
  );
}
